"""initial schema

Revision ID: d72538c7b773
Revises: 
Create Date: 2026-06-20 14:59:37.533797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd72538c7b773'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('books',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('owner_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('author', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('WANT_TO_READ', 'READING', 'FINISHED', name='bookstatus'), nullable=False),
    sa.Column('total_pages', sa.Integer(), nullable=True),
    sa.Column('current_page', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('current_page >= 0', name='ck_book_current_page_nonneg'),
    sa.CheckConstraint('rating IS NULL OR (rating >= 1 AND rating <= 5)', name='ck_book_rating_range'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_books_owner_id'), ['owner_id'], unique=False)

    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_refresh_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('shelves',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('owner_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shelves', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shelves_owner_id'), ['owner_id'], unique=False)

    op.create_table('activity_events',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('actor_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('type', sa.Enum('BOOK_ADDED', 'BOOK_STATUS_CHANGED', 'BOOK_LENT', 'BOOK_RETURNED', 'SHELF_SHARED', 'SHELF_ROLE_CHANGED', 'SHELF_COLLABORATOR_REMOVED', name='activitytype'), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('shelf_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('book_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.ForeignKeyConstraint(['shelf_id'], ['shelves.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activity_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activity_events_created_at'), ['created_at'], unique=False)

    op.create_table('lendings',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('book_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('lender_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('borrower_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('lent_at', sa.DateTime(), nullable=False),
    sa.Column('returned_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.ForeignKeyConstraint(['borrower_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['lender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lendings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lendings_book_id'), ['book_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lendings_borrower_id'), ['borrower_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lendings_lender_id'), ['lender_id'], unique=False)
        batch_op.create_index('uq_active_lending_per_book', ['book_id'], unique=True, postgresql_where=sa.text('returned_at IS NULL'))

    op.create_table('shelf_books',
    sa.Column('shelf_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('book_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.ForeignKeyConstraint(['shelf_id'], ['shelves.id'], ),
    sa.PrimaryKeyConstraint('shelf_id', 'book_id')
    )
    op.create_table('shelf_shares',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('shelf_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('role', sa.Enum('EDITOR', 'VIEWER', name='shelfrole'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['shelf_id'], ['shelves.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shelf_id', 'user_id', name='uq_shelf_user_share')
    )
    with op.batch_alter_table('shelf_shares', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shelf_shares_shelf_id'), ['shelf_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shelf_shares_user_id'), ['user_id'], unique=False)

    op.create_table('activity_recipients',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('event_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['activity_events.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activity_recipients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activity_recipients_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_recipients_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_recipients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_recipients_user_id'))
        batch_op.drop_index(batch_op.f('ix_activity_recipients_event_id'))

    op.drop_table('activity_recipients')
    with op.batch_alter_table('shelf_shares', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shelf_shares_user_id'))
        batch_op.drop_index(batch_op.f('ix_shelf_shares_shelf_id'))

    op.drop_table('shelf_shares')
    op.drop_table('shelf_books')
    with op.batch_alter_table('lendings', schema=None) as batch_op:
        batch_op.drop_index('uq_active_lending_per_book', postgresql_where=sa.text('returned_at IS NULL'))
        batch_op.drop_index(batch_op.f('ix_lendings_lender_id'))
        batch_op.drop_index(batch_op.f('ix_lendings_borrower_id'))
        batch_op.drop_index(batch_op.f('ix_lendings_book_id'))

    op.drop_table('lendings')
    with op.batch_alter_table('activity_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_events_created_at'))

    op.drop_table('activity_events')
    with op.batch_alter_table('shelves', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shelves_owner_id'))

    op.drop_table('shelves')
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_user_id'))

    op.drop_table('refresh_tokens')
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_books_owner_id'))

    op.drop_table('books')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
